[features]
seeds = false
skip-lint = false
[programs.localnet]
twitter = "D6wJsHUyGE3Ng6hgyXiSQ1oifSgaJVNgU2LhDWzyKZQU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/suleymanhanyyev/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
